name: Generate F-Droid repo

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
  - cron: "00 1,13 * * *"

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#         with:
#           ifs: true

#       - name: Checkout LFS objects
#         run: git lfs checkout
      

      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: fdroid/

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

#       - name: Restore correct mtime
#         run: |
#           sudo apt install git-restore-mtime 
#           git restore-mtime

      - name: Install F-Droid server software
        run: |
         sudo add-apt-repository ppa:fdroid/fdroidserver &&
         sudo apt-get update && sudo apt-get upgrade &&
         sudo apt-get install apksigner dexdump opensc s3cmd zipalign android-sdk &&
         sudo apt-get install fdroidserver

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: BSFishy/pip-action@v1
        with:
          requirements: 'requirements.txt'

      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
